name: Node.js CI

# main branch에서 push 하거나 pr 했을 때
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    
    steps:
    # 원격 저장소에 있는 코드를 내려 받아라!
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          # 의존성 목록 설치
          # package-lock.json 이 꼭 존재, 없으면 에러
          # package-lock.json 기반으로 의존성 설치, package.sjon은 버전 매칭 밸리데이션 용도로 사용
          # 두 파일 사이의 버전이 같아야함
          npm ci
          # 실행하면 node_modules 삭제한 후, 의존성 한번에 설치
          # 이미 버전이 명시된 package-lock.json을 기반으로 설치하기 때문에 설치할 버전을 알아야내야하는 npm install 보다 빠름
          
          # 배포 파일 만들 때
          npm run build
