name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print PW
        env :
          PW : ${{serects.PASSWORD}}
        run: echo "MY PW ${Pw}"
